### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/mobx-remotedev#1]
* [ ] Monitoring
* [ ] Time travelling
* [ ] Export / Import state
* [ ] Dispatch actions remotely
* [ ] Cancel actions
* [ ] Support for non-browser environment (unify with [`remotedev`](https://github.com/zalmoxisus/remotedev))

**Comment by mweststrate** [comment]
Hi @zalmoxisus  / @antitoxic 

I currently playing with the idea of a standardized state container, see this repo: https://github.com/mweststrate/mobx-state-tree, I'll try to push some more info to the readme next week, but I might be a very good fit for standardized time travelling etc etc.

**Comment by mweststrate** [comment]
Hey @zalmoxisus / @antitoxic here same updates on my work on the state tree (it will be part of an upcoming talk). Let me know what you think! It restricts state to be a tree, which made integration with the devtools surprisingly simple! Not entirely sure I did the middleware right, but seems to work :). 

I didn't implement the replay yet though, is there an api that allows me to connect to the slider, to be able to replay actions?

https://github.com/mweststrate/mobx-state-tree/blob/0d0c5e1c70ff0dcea7fce53d1f10d97e661f33de/examples/boxes/src/index.js#L18
https://github.com/mweststrate/mobx-state-tree/blob/0d0c5e1c70ff0dcea7fce53d1f10d97e661f33de/examples/redux-todomvc/src/index.js#L10
https://github.com/mweststrate/mobx-state-tree/blob/0d0c5e1c70ff0dcea7fce53d1f10d97e661f33de/src/interop/redux-devtools.ts

![screenshot from 2016-10-10 23-21-00](https://cloud.githubusercontent.com/assets/1820292/19251928/228effa4-8f42-11e6-9e55-d8d9274441ae.png)
![screenshot from 2016-10-10 23-19-38](https://cloud.githubusercontent.com/assets/1820292/19251935/336ecfca-8f42-11e6-96e0-1fec58674cc0.png)

**Comment by antitoxic** [comment]
As far as I know the Slider monitor just reverts to a previous state and then reapplies actions after that point. That's all what replaying does. Am I missing something?

In any case, I am not familiar with mobx-state-tree. I've added an issue there.

**Comment by mweststrate** [comment]
Yeah so the basic question is, where does it apply them *to*. If the devtools are loaded as middleware it has access to the store, but how does it revert to the base state. Dispatch `@@INIT`? If the `send(action, state)` api is used, and the slider is used, there should probably be an event that receives the state that needs to be restored, so that it can be applied to the original store. But I couldn't find such an event, did I overlook something @zalmoxisus ?

**Comment by zalmoxisus** [comment]
@mweststrate, looks impressive! For supporting the slider you just need to add `subscribe` and set the state when monitor dispatch `JUMP_TO_STATE`, like in [the example](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#connectconfig). [Here](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L63)'s the implementation, and there are other monitor actions you can find there. Only the new `LOCK_CHANGES` isn't implemented yet as it's not possible in MobX to freeze any future changes except those from devtools (maybe in `mobx-state-tree` will be possible). [Here](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83)'s a blog post about why we need that.

@antitoxic, Slider just set a state received from the extension. What yo described is for canceling (skipping) actions.

**Comment by mweststrate** [comment]
awesome, that was the missing piece (skimmed the docs but completely missed it somehow). Gonna play with it! will you guys visit ReactNL or ReactiveConf?

**Comment by zalmoxisus** [comment]
@mweststrate, unfortunately not. Feel free to ping me if you have other questions or suggestions to improve the workflow.

The initial state is [stored on the client part](https://github.com/zalmoxisus/mobx-remotedev/blob/master/src/monitorActions.js#L47), the extension knows only the committed state which becomes different after clicking `COMMIT`.

**Comment by zalmoxisus** [comment]
@mweststrate, also you could use [`remotedev`](https://github.com/zalmoxisus/remotedev)'s [`connectViaExtension`](https://github.com/zalmoxisus/remotedev/blob/master/src/devTools.js#L133), which will bypass the extension when not available and use sockets to allow using it not only for web apps, but also for React Native, Cordova, server side... We're including it here, but of course it shouldn't be included by default in `mobx-state-tree`.

**Comment by antitoxic** [comment]
@mweststrate sadly I'm not going to any of the confs due to freelance wrap-ups before starting a new fulltime position. 

@zalmoxisus Alright, I thought `JUMP_TO_STATE` runs just once and the then actions are reapplied. If I understand correctly the slider just do `JUMP_TO_STATE` on every step.

**Comment by zalmoxisus** [comment]
@antitoxic, yes, and for every step it returns the index for Redux, and the state on the current index for non-Redux apps.

**Comment by zalmoxisus** [comment]
@mweststrate, just now got a chance to look into `mobx-state-tree`.

Actually, there's no need to reimplement `mobx-remotedev` there. Since the models are meant to handle the state (as Redux' reducers) you could just pass them to the extension, and use it almost out of the box by connecting to its store. The same as in [the example with React](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter/components/Counter.js). I made [a rough example](https://github.com/zalmoxisus/mobx-state-tree/commit/0dd905d3fd3e1581deda7cca2e0c11243b849d12).

I guess you could implement something as Redux store enhancer and it would be even simpler

BTW, good luck with your tomorrow's talk!
